defaults:
  - /onpolicy_mujoco_config_cfg_def@_here_
  - _self_
  - algo: base # raise error if algo is not specified
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

seed: 0
device: '0'
task: ???
norm_obs: true
train_frames: 200_000_000
eval_frames: 5_000_000
log_frames: 100_000
num_envs: ${algo.num_envs}
rollout_length: ${algo.rollout_length}
env_mode: async
async_shared_memory: true
async_context: null
debug_finite_checks: false
max_episode_steps: null
log:
  dir: logs
  tag: debug
  save_ckpt: false
  save_video: false
  project: ???
  entity: ???
  wandb: true
  wandb_mode: online
  group: null
  name: null
  tags: null
eval:
  num_episodes: 10
  num_samples: 1
